// flow-typed signature: 1920a3111d53a7a671ce35978ff66ea0
// flow-typed version: <<STUB>>/@monorepo_v1.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@monorepo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@monorepo' {
  declare module.exports: any;
}

declare module '@monorepo/backend/Data/Users.json' {
  declare module.exports: any;
}

declare module '@monorepo/backend/Data/Rooms.json'{
  declare module.exports: any;
}

declare module '@monorepo/backend/Data/Talks.json'{
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@monorepo/web-client/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@monorepo/web-client/webpack.config.js' {
  declare module.exports: $Exports<'@monorepo/web-client/webpack.config'>;
}
