// flow-typed signature: 6063a3a4451b8747df31cac7880d9b6e
// flow-typed version: <<STUB>>/react-spinners-css_v^1.1.7/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinners-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinners-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinners-css/dist/Circle' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Default' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/DualRing' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Ellipsis' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Facebook' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Grid' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Heart' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Hourglass' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Orbitals' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Ouroboro' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Ring' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Ripple' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Roller' {
  declare module.exports: any;
}

declare module 'react-spinners-css/dist/Spinner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinners-css/dist/Circle/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Circle'>;
}
declare module 'react-spinners-css/dist/Circle/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Circle'>;
}
declare module 'react-spinners-css/dist/Default/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Default'>;
}
declare module 'react-spinners-css/dist/Default/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Default'>;
}
declare module 'react-spinners-css/dist/DualRing/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/DualRing'>;
}
declare module 'react-spinners-css/dist/DualRing/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/DualRing'>;
}
declare module 'react-spinners-css/dist/Ellipsis/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Ellipsis'>;
}
declare module 'react-spinners-css/dist/Ellipsis/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Ellipsis'>;
}
declare module 'react-spinners-css/dist/Facebook/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Facebook'>;
}
declare module 'react-spinners-css/dist/Facebook/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Facebook'>;
}
declare module 'react-spinners-css/dist/Grid/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Grid'>;
}
declare module 'react-spinners-css/dist/Grid/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Grid'>;
}
declare module 'react-spinners-css/dist/Heart/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Heart'>;
}
declare module 'react-spinners-css/dist/Heart/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Heart'>;
}
declare module 'react-spinners-css/dist/Hourglass/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Hourglass'>;
}
declare module 'react-spinners-css/dist/Hourglass/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Hourglass'>;
}
declare module 'react-spinners-css/dist/index' {
  declare module.exports: $Exports<'react-spinners-css/dist'>;
}
declare module 'react-spinners-css/dist/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist'>;
}
declare module 'react-spinners-css/dist/Orbitals/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Orbitals'>;
}
declare module 'react-spinners-css/dist/Orbitals/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Orbitals'>;
}
declare module 'react-spinners-css/dist/Ouroboro/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Ouroboro'>;
}
declare module 'react-spinners-css/dist/Ouroboro/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Ouroboro'>;
}
declare module 'react-spinners-css/dist/Ring/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Ring'>;
}
declare module 'react-spinners-css/dist/Ring/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Ring'>;
}
declare module 'react-spinners-css/dist/Ripple/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Ripple'>;
}
declare module 'react-spinners-css/dist/Ripple/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Ripple'>;
}
declare module 'react-spinners-css/dist/Roller/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Roller'>;
}
declare module 'react-spinners-css/dist/Roller/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Roller'>;
}
declare module 'react-spinners-css/dist/Spinner/index' {
  declare module.exports: $Exports<'react-spinners-css/dist/Spinner'>;
}
declare module 'react-spinners-css/dist/Spinner/index.js' {
  declare module.exports: $Exports<'react-spinners-css/dist/Spinner'>;
}
