// flow-typed signature: f156b937eec2690b80a903d3c8e6dc8c
// flow-typed version: <<STUB>>/@bit/joshk.react-spinners-css.facebook_v^1.1.7/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bit/joshk.react-spinners-css.facebook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bit/joshk.react-spinners-css.facebook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bit/joshk.react-spinners-css.facebook/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@bit/joshk.react-spinners-css.facebook/dist/index' {
  declare module.exports: $Exports<'@bit/joshk.react-spinners-css.facebook/dist'>;
}
declare module '@bit/joshk.react-spinners-css.facebook/dist/index.js' {
  declare module.exports: $Exports<'@bit/joshk.react-spinners-css.facebook/dist'>;
}
declare module '@bit/joshk.react-spinners-css.facebook/index' {
  declare module.exports: $Exports<'@bit/joshk.react-spinners-css.facebook'>;
}
declare module '@bit/joshk.react-spinners-css.facebook/index.js' {
  declare module.exports: $Exports<'@bit/joshk.react-spinners-css.facebook'>;
}
