// flow-typed signature: a4fe25bc873bddf2b14e368f58d26416
// flow-typed version: <<STUB>>/@jolt-us/jolt-mobx_v2.0.3/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jolt-us/jolt-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jolt-us/jolt-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jolt-us/jolt-mobx/lib/AsyncProperty' {
  declare module.exports: any;
}

declare module '@jolt-us/jolt-mobx/lib/connect' {
  declare module.exports: any;
}

declare module '@jolt-us/jolt-mobx/lib/jolt-mobx' {
  declare module.exports: any;
}

declare module '@jolt-us/jolt-mobx/lib/Observable' {
  declare module.exports: any;
}

declare module '@jolt-us/jolt-mobx/lib/Provider' {
  declare module.exports: any;
}

declare module '@jolt-us/jolt-mobx/types/declare/Mocha' {
  declare module.exports: any;
}

declare module '@jolt-us/jolt-mobx/types/declare/process' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jolt-us/jolt-mobx/lib/AsyncProperty.js' {
  declare module.exports: $Exports<'@jolt-us/jolt-mobx/lib/AsyncProperty'>;
}
declare module '@jolt-us/jolt-mobx/lib/connect.js' {
  declare module.exports: $Exports<'@jolt-us/jolt-mobx/lib/connect'>;
}
declare module '@jolt-us/jolt-mobx/lib/jolt-mobx.js' {
  declare module.exports: $Exports<'@jolt-us/jolt-mobx/lib/jolt-mobx'>;
}
declare module '@jolt-us/jolt-mobx/lib/Observable.js' {
  declare module.exports: $Exports<'@jolt-us/jolt-mobx/lib/Observable'>;
}
declare module '@jolt-us/jolt-mobx/lib/Provider.js' {
  declare module.exports: $Exports<'@jolt-us/jolt-mobx/lib/Provider'>;
}
declare module '@jolt-us/jolt-mobx/types/declare/Mocha.js' {
  declare module.exports: $Exports<'@jolt-us/jolt-mobx/types/declare/Mocha'>;
}
declare module '@jolt-us/jolt-mobx/types/declare/process.js' {
  declare module.exports: $Exports<'@jolt-us/jolt-mobx/types/declare/process'>;
}
